# Generated by Django 6.0.3 on 2026-03-11 18:57

import django.db.models.deletion
import innovation_platformlu.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=innovation_platformlu.models.generate_room_code, max_length=10, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('challenge', 'مشكلة/تحدي'), ('idea', 'فكرة/حل')], default='challenge', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(blank=True, choices=[('health', 'صحي'), ('operational', 'تشغيلي'), ('technical', 'تقني'), ('service', 'خدمي'), ('financial', 'مالي'), ('administrative', 'إداري'), ('research', 'بحثي/تطوير'), ('other', 'أخرى')], default='', max_length=30)),
                ('impact', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('review', 'قيد المراجعة'), ('progress', 'قيد التنفيذ'), ('done', 'منفذ')], default='new', max_length=20)),
                ('pos_x', models.IntegerField(default=40)),
                ('pos_y', models.IntegerField(default=40)),
                ('width', models.IntegerField(default=520)),
                ('height', models.IntegerField(default=320)),
                ('is_checked', models.BooleanField(default=False)),
                ('challenge_date', models.DateField(blank=True, null=True)),
                ('challenge_title', models.CharField(blank=True, default='', max_length=200)),
                ('challenge_description', models.TextField(blank=True, default='')),
                ('has_suggested_solution', models.BooleanField(default=False)),
                ('suggested_solution', models.TextField(blank=True, default='')),
                ('challenge_notes', models.TextField(blank=True, default='')),
                ('technologies_used', models.CharField(blank=True, default='', max_length=255)),
                ('idea_name', models.CharField(blank=True, default='', max_length=220)),
                ('idea_launch_date', models.DateField(blank=True, null=True)),
                ('idea_leader_or_team', models.CharField(blank=True, default='', max_length=220)),
                ('idea_description', models.TextField(blank=True, default='')),
                ('idea_type', models.CharField(blank=True, choices=[('service_improvement', 'تحسين خدمة'), ('tech_product', 'منتج / حل تقني'), ('process_improvement', 'تحسين إجراء'), ('ux', 'تجربة مستخدم'), ('rnd', 'بحث / تطوير')], default='', max_length=40)),
                ('idea_stage', models.CharField(blank=True, choices=[('study', 'قيد الدراسة'), ('progress', 'قيد التنفيذ'), ('done', 'مكتملة'), ('stopped', 'متوقفة')], default='', max_length=20)),
                ('stage', models.CharField(blank=True, default='', max_length=150)),
                ('idea_notes', models.TextField(blank=True, default='')),
                ('ai_solutions', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_platformlu.department')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='innovation_platformlu.room')),
            ],
        ),
    ]
