# Generated by Django 6.0 on 2026-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation_platformlu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='administration_department',
            field=models.CharField(blank=True, choices=[('sandbox', 'ادارة الساندبوكس'), ('ai', 'ادارة الذكاء الاصطناعي'), ('medical_consulting', 'الادارة العامة للاستشارات الطبية'), ('cardiology', 'قسم القلب'), ('radiology', 'قسم الاشعة'), ('stroke', 'قسم الجلطات'), ('icu', 'قسم العناية المركزة'), ('hr', 'ادارة الموارد البشرية'), ('quality', 'ادارة الجودة'), ('shared_services', 'ادارة الخدمات المشتركة'), ('digital_enablement', 'ادارة التمكين الرقمي'), ('data', 'ادارة البيانات'), ('finance', 'الادارة المالية'), ('insurance', 'ادارة التامين الصحي')], default='', max_length=100),
        ),
    ]
