# Generated by Django 5.2.11 on 2026-02-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('challenge', 'Challenge'), ('initiative', 'Initiative'), ('innovation', 'Innovation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('impact', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('progress', 'In Progress'), ('done', 'Completed'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
