# Generated by Django 5.2.11 on 2026-02-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('column', models.CharField(choices=[('define', 'Define'), ('ideate', 'Ideate'), ('prototype', 'Prototype')], default='define', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='department',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='impact',
        ),
    ]
