# Generated by Django 5.2.11 on 2026-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boarditem_remove_submission_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='department',
            field=models.CharField(choices=[('sandbox', 'إدارة الساندبوكس'), ('ai', 'إدارة الذكاء الاصطناعي'), ('consulting', 'الإدارة العامة للاستشارات الطبية'), ('cardiology', 'قسم القلب'), ('radiology', 'قسم الأشعة'), ('strokes', 'قسم الجلطات'), ('icu', 'قسم العناية المركزة'), ('hr', 'إدارة الموارد البشرية'), ('quality', 'إدارة الجودة'), ('shared_services', 'إدارة الخدمات المشتركة'), ('digital_empowerment', 'إدارة التمكين الرقمي'), ('data', 'إدارة البيانات'), ('finance', 'الإدارة المالية'), ('insurance', 'إدارة التأمين الصحي')], default='sandbox', max_length=50),
        ),
        migrations.AlterField(
            model_name='boarditem',
            name='column',
            field=models.CharField(choices=[('define', 'Define'), ('ideate', 'Ideate'), ('prototype', 'Prototype')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('challenge', 'Challenge'), ('initiative', 'Initiative')], max_length=20),
        ),
    ]
